zuul:
  routes:
    account:
      serviceId: ACCOUNT-SERVICE

server:
  port: 5555
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: api-gateway
#management:
  #security:
    #enabled: false
#security:
  #basic:
    #enabled: false